### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lstark-uibk** [lstark-uibk/Manual_Pyeakfitter#30]
<class 'RuntimeError'> wrapped C/C++ object of type PlotCurveItem has been deleted <traceback object at 0x00000231CF04BA40>
Traceback (most recent call last):
  File "C:\Anaconda\envs\envUrs2023_05_32\lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py", line 222, in mouseReleaseEvent
    if self.sendClickEvent(cev[0]):
  File "C:\Anaconda\envs\envUrs2023_05_32\lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py", line 364, in sendClickEvent
    if not item.isVisible() or not item.isEnabled():
RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

**Comment by lstark-uibk** [comment]
when deleting H4H+ which was at 29 somehow

**Comment by lstark-uibk** [comment]
so somehow when clicking a line and releasing, we already deleted the line and it still wants to do something with it

**Comment by lstark-uibk** [comment]
Maybe it is because when we delete the Item it is still here?

**Comment by lstark-uibk** [comment]
still this error
RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted
